apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: judgemesh

resources:
  - ../../base/submit-service
  - ../../base/judge-worker
  # TODO 加入 gateway / user-service / problem-service / judge-dispatcher

# dev 环境差异:1 副本、资源减半、本地镜像
patches:
  - target: { kind: Deployment, name: submit-service }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: judge-worker }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
