apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: judgemesh

resources:
  - ../../base/submit-service
  - ../../base/judge-worker
  # TODO 加入 gateway / user-service / problem-service / judge-dispatcher
